### ISSUE TITLE
Error alfred-link in Alfred 4

### ISSUE THREAD

**Issue by denostr** [liutkin/alfred-privatbank-currency-exchange#8]
```
Error: Command failed with exit code 1 (EPERM): alfred-link
    at makeError (/usr/local/lib/node_modules/alfred-privatbank-currency-exchange/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/alfred-privatbank-currency-exchange/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/local/lib/node_modules/alfred-privatbank-currency-exchange/node_modules/alfy/init.js:7:3 {
  command: 'alfred-link',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'Error: Permission denied to read Alfred preferences at location /Users/denis/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/alfred-privatbank-currency-exchange/node_modules/resolve-alfred-prefs/index.js:44:9)',
  all: 'Error: Permission denied to read Alfred preferences at location /Users/denis/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/alfred-privatbank-currency-exchange/node_modules/resolve-alfred-prefs/index.js:44:9)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
```

Think need to update **alfy** and it dependency **alfred-link** to make it work

**Comment by denostr** [comment]
Dont know what is was, from that time changed my macbook, and it works now
